# Generated by Django 6.0.5 on 2026-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن اضطراری'),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='اولین مراجعه'),
        ),
    ]
