# Generated by Django 6.0.5 on 2026-05-19 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_emergency_phone_patient_father_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_booklet',
            field=models.CharField(choices=[('none', 'ندارد'), ('social_security', 'تأمین اجتماعی'), ('health_services', 'خدمات بهداشتی درمانی'), ('military', 'نیروهای مسلح'), ('other', 'سایر')], default='none', max_length=20, verbose_name='نوع دفترچه'),
        ),
        migrations.AddField(
            model_name='patient',
            name='routine_medications',
            field=models.TextField(blank=True, verbose_name='داروهای روتین'),
        ),
        migrations.CreateModel(
            name='ReferralLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_doctor', models.CharField(blank=True, max_length=200, verbose_name='پزشک/مرکز مقصد')),
                ('date', models.DateField(verbose_name='تاریخ ارجاع')),
                ('description', models.TextField(verbose_name='شرح ارجاع')),
                ('file', models.FileField(blank=True, null=True, upload_to='referrals/', verbose_name='فایل ضمیمه')),
                ('status', models.CharField(choices=[('sent', 'ارسال شده'), ('received', 'دریافت شده'), ('answered', 'پاسخ داده شده')], default='sent', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_creations', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('from_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent', to=settings.AUTH_USER_MODEL, verbose_name='پزشک ارجاع دهنده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_letters', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نامه ارجاع',
                'verbose_name_plural': 'نامه\u200cهای ارجاع',
                'ordering': ['-date'],
            },
        ),
    ]
