# Generated by Django 6.0.5 on 2026-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_insurance_booklet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره پرونده'),
        ),
    ]
