# Generated by Django 6.0.5 on 2026-05-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_file_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره پرونده'),
        ),
    ]
