# Generated by Django 6.0.5 on 2026-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_file_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralletter',
            name='drug',
            field=models.CharField(blank=True, max_length=500, verbose_name='داروی مصرفی'),
        ),
    ]
