# Generated by Django 6.0.5 on 2026-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_referralletter_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=10, verbose_name='جنسیت'),
        ),
    ]
