# Generated by Django 6.0.5 on 2026-05-24 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_referralletter_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('reply', models.TextField(blank=True, verbose_name='پاسخ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='patients.patient', verbose_name='بیمار')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام پشتیبانی',
                'verbose_name_plural': 'پیام\u200cهای پشتیبانی',
                'ordering': ['-created_at'],
            },
        ),
    ]
