# Generated by Django 6.0.5 on 2026-05-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_support_message_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حذف کننده'),
        ),
        migrations.AddField(
            model_name='patient',
            name='education',
            field=models.CharField(blank=True, choices=[('ciclu', 'سیکل'), ('diplom', 'دیپلم'), ('super_diplom', 'فوق دیپلم'), ('licence', 'لیسانس'), ('master', 'فوق لیسانس'), ('doctora', 'دکترا')], max_length=20, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AddField(
            model_name='patient',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شغل'),
        ),
        migrations.AddField(
            model_name='patient',
            name='old_file_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرونده قدیمی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره پرونده'),
        ),
    ]
