# Generated by Django 6.0.5 on 2026-05-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patient_deleted_at_patient_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, error_messages={'unique': 'این شماره پرونده قبلاً ثبت شده است'}, max_length=20, null=True, unique=True, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(db_index=True, error_messages={'unique': 'این کد ملی قبلاً برای بیمار دیگری ثبت شده است'}, max_length=10, unique=True, verbose_name='کد ملی'),
        ),
    ]
