# Generated by Django 6.0.6 on 2026-06-09 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_patient_created_by_alter_patient_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام برچسب')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='رنگ برچسب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'برچسب بیمار',
                'verbose_name_plural': 'برچسب\u200cهای بیمار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='patients.patient', verbose_name='بیمار')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='patients.patienttag', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'اختصاص برچسب',
                'verbose_name_plural': 'اختصاص برچسب\u200cها',
                'unique_together': {('patient', 'tag')},
            },
        ),
    ]
