# Generated by Django 6.0.6 on 2026-06-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patienttag_patienttagassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='توکن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'نشست پورتال بیمار',
                'verbose_name_plural': 'نشست\u200cهای پورتال بیمار',
            },
        ),
        migrations.CreateModel(
            name='PortalOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='کد تایید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_otps', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'کد تایید پورتال',
                'verbose_name_plural': 'کدهای تایید پورتال',
            },
        ),
    ]
