# Generated by Django 6.0.6 on 2026-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patientportalsession_portalotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='job',
            field=models.CharField(blank=True, choices=[('doctor', 'پزشک'), ('midwife', 'ماما'), ('engineer', 'مهندس'), ('nurse', 'پرستار'), ('employee', 'کارمند'), ('worker', 'کارگر'), ('housewife', 'خانه دار'), ('freelance', 'آزاد')], max_length=50, null=True, verbose_name='شغل'),
        ),
    ]
