# Generated by Django 5.2.15 on 2026-06-15 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_nationa_70cc77_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_phone_fc49bb_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='address_enc',
            field=models.TextField(blank=True, verbose_name='آدرس (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_raw',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس (قدیمی)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_phone_enc',
            field=models.TextField(blank=True, verbose_name='تلفن اضطراری (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_phone_raw',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن اضطراری (قدیمی)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history_enc',
            field=models.TextField(blank=True, verbose_name='تاریخچه پزشکی (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history_raw',
            field=models.TextField(blank=True, null=True, verbose_name='تاریخچه پزشکی (قدیمی)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id_enc',
            field=models.TextField(blank=True, verbose_name='کد ملی (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='هش کد ملی'),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id_raw',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='کد ملی (قدیمی)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_enc',
            field=models.TextField(blank=True, verbose_name='تلفن (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='هش تلفن'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_raw',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن (قدیمی)'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id_hash'], name='patients_pa_nationa_d220b8_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_hash'], name='patients_pa_phone_h_e16f32_idx'),
        ),
    ]
