# Generated by Django 6.0.6 on 2026-06-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_migrate_existing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='patient',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='support_messages', to='patients.patient',
                verbose_name='بیمار',
            ),
        ),
    ]
