# Generated by Django 6.0.5 on 2026-05-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('hour', models.IntegerField(default=3, verbose_name='ساعت')),
                ('minute', models.IntegerField(default=0, verbose_name='دقیقه')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرا')),
            ],
            options={
                'verbose_name': 'تنظیم زمان پشتیبان\u200cگیری خودکار',
                'verbose_name_plural': 'تنظیم زمان پشتیبان\u200cگیری خودکار',
            },
        ),
    ]
