# Generated by Django 6.0.5 on 2026-05-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
