# Generated by Django 6.0.5 on 2026-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_alter_backupschedule_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, verbose_name='نام فایل')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='حجم')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'شکست')], max_length=20, verbose_name='وضعیت')),
                ('engine', models.CharField(blank=True, max_length=50, verbose_name='موتور دیتابیس')),
                ('cloud_uploaded', models.BooleanField(default=False, verbose_name='آپلود ابری')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'لاگ بکاپ',
                'verbose_name_plural': 'لاگ\u200cهای بکاپ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='cloud_sync_enabled',
            field=models.BooleanField(default=False, verbose_name='همگام\u200cسازی ابری'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='encrypt_backup',
            field=models.BooleanField(default=False, verbose_name='رمزنگاری بکاپ'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='retention_days',
            field=models.IntegerField(default=30, verbose_name='نگهداری بکاپ (روز)'),
        ),
    ]
