# Generated by Django 4.2.30 on 2026-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backuplog_backupschedule_cloud_sync_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(blank=True, verbose_name='توکن رفرش')),
                ('access_token', models.TextField(blank=True, verbose_name='توکن دسترسی')),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=500, verbose_name='آدرس توکن')),
                ('client_id', models.CharField(blank=True, max_length=500, verbose_name='شناسه کلاینت')),
                ('client_secret', models.CharField(blank=True, max_length=500, verbose_name='رمز کلاینت')),
                ('scopes', models.TextField(default='https://www.googleapis.com/auth/drive.file', verbose_name='دسترسی\u200cها')),
                ('connected', models.BooleanField(default=False, verbose_name='متصل')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اتصال')),
                ('last_upload_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین آپلود')),
            ],
            options={
                'verbose_name': 'توکن Google Drive',
                'verbose_name_plural': 'توکن\u200cهای Google Drive',
            },
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='cloud_sync_enabled',
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='google_drive_auto_upload',
            field=models.BooleanField(default=False, verbose_name='آپلود خودکار گوگل درایو'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='google_drive_interval_hours',
            field=models.IntegerField(default=8, verbose_name='فاصله آپلود (ساعت)'),
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='cloud_uploaded',
            field=models.BooleanField(default=False, verbose_name='آپلود گوگل درایو'),
        ),
    ]
