# Generated by Django 4.2.30 on 2026-06-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_googledrivetoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='هاست SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='پورت SMTP')),
                ('use_tls', models.BooleanField(default=True, verbose_name='استفاده از TLS')),
                ('sender_email', models.CharField(blank=True, max_length=255, verbose_name='ایمیل فرستنده')),
                ('sender_password', models.CharField(blank=True, max_length=255, verbose_name='رمز ایمیل')),
                ('recipient_email', models.CharField(blank=True, max_length=255, verbose_name='ایمیل گیرنده')),
                ('auto_send', models.BooleanField(default=False, verbose_name='ارسال خودکار پس از بکاپ')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ارسال')),
            ],
            options={
                'verbose_name': 'تنظیم ایمیل پشتیبان',
                'verbose_name_plural': 'تنظیم ایمیل پشتیبان',
            },
        ),
        migrations.DeleteModel(
            name='GoogleDriveToken',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='google_drive_auto_upload',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='google_drive_interval_hours',
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='cloud_uploaded',
            field=models.BooleanField(default=False, verbose_name='ارسال ایمیل'),
        ),
    ]
