# Generated by Django 6.0.6 on 2026-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_emailbackupconfig_delete_googledrivetoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubBackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(blank=True, max_length=255, verbose_name='ریپازیتوری (owner/repo)')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='توکن دسترسی GitHub')),
                ('auto_upload', models.BooleanField(default=False, verbose_name='آپلود خودکار پس از بک\u200cآپ')),
                ('keep_last_n', models.IntegerField(default=10, verbose_name='نگهداری آخرین N release')),
                ('last_upload_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین آپلود')),
                ('last_upload_file', models.CharField(blank=True, max_length=500, verbose_name='آخرین فایل آپلود شده')),
                ('last_upload_status', models.CharField(blank=True, max_length=50, verbose_name='وضعیت آخرین آپلود')),
            ],
            options={
                'verbose_name': 'تنظیم GitHub پشتیبان',
                'verbose_name_plural': 'تنظیمات GitHub پشتیبان',
            },
        ),
        migrations.AddField(
            model_name='backuplog',
            name='github_uploaded',
            field=models.BooleanField(default=False, verbose_name='آپلود به GitHub'),
        ),
    ]
