# Generated by Django 4.2.30 on 2026-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_add_github_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubbackupconfig',
            name='github_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام کاربری گیت\u200cهاب'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='github_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شناسه کاربر گیت\u200cهاب'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='oauth_token',
            field=models.TextField(blank=True, verbose_name='توکن OAuth گیت\u200cهاب'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='oauth_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انقضای توکن OAuth'),
        ),
    ]
