# Generated by Django 4.2.30 on 2026-06-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0007_githubbackupconfig_github_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubbackupconfig',
            name='oauth_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client ID اپ گیت\u200cهاب'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='oauth_client_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client Secret اپ گیت\u200cهاب'),
        ),
    ]
