# Generated by Django 5.2.15 on 2026-06-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0008_githubbackupconfig_oauth_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailbackupconfig',
            name='sender_password',
        ),
        migrations.RemoveField(
            model_name='githubbackupconfig',
            name='oauth_client_secret',
        ),
        migrations.RemoveField(
            model_name='githubbackupconfig',
            name='oauth_token',
        ),
        migrations.RemoveField(
            model_name='githubbackupconfig',
            name='token',
        ),
        migrations.AddField(
            model_name='emailbackupconfig',
            name='sender_password_enc',
            field=models.TextField(blank=True, verbose_name='رمز ایمیل (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='emailbackupconfig',
            name='sender_password_raw',
            field=models.CharField(blank=True, max_length=255, verbose_name='رمز ایمیل (قدیمی)'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='oauth_client_secret_enc',
            field=models.TextField(blank=True, verbose_name='Client Secret اپ گیت\u200cهاب (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='oauth_client_secret_raw',
            field=models.CharField(blank=True, max_length=255, verbose_name='Client Secret اپ گیت\u200cهاب (قدیمی)'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='oauth_token_enc',
            field=models.TextField(blank=True, verbose_name='توکن OAuth گیت\u200cهاب (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='oauth_token_raw',
            field=models.TextField(blank=True, verbose_name='توکن OAuth گیت\u200cهاب (قدیمی)'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='token_enc',
            field=models.TextField(blank=True, verbose_name='توکن دسترسی GitHub (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='githubbackupconfig',
            name='token_raw',
            field=models.CharField(blank=True, max_length=255, verbose_name='توکن دسترسی GitHub (قدیمی)'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='encrypt_backup',
            field=models.BooleanField(default=True, verbose_name='رمزنگاری بکاپ'),
        ),
    ]
