# Generated by Django 5.2.15 on 2026-06-15 00:35

from django.db import migrations
from utils.encryption import encrypt_value


def migrate_backup_data(apps, schema_editor):
    EmailBackupConfig = apps.get_model('backup', 'EmailBackupConfig')
    for obj in EmailBackupConfig.objects.all():
        if obj.sender_password_raw and not obj.sender_password_enc:
            obj.sender_password_enc = encrypt_value(obj.sender_password_raw)
            obj.save(update_fields=['sender_password_enc'])

    GitHubBackupConfig = apps.get_model('backup', 'GitHubBackupConfig')
    for obj in GitHubBackupConfig.objects.all():
        changed = False
        if obj.token_raw and not obj.token_enc:
            obj.token_enc = encrypt_value(obj.token_raw)
            changed = True
        if obj.oauth_token_raw and not obj.oauth_token_enc:
            obj.oauth_token_enc = encrypt_value(obj.oauth_token_raw)
            changed = True
        if obj.oauth_client_secret_raw and not obj.oauth_client_secret_enc:
            obj.oauth_client_secret_enc = encrypt_value(obj.oauth_client_secret_raw)
            changed = True
        if changed:
            obj.save(update_fields=['token_enc', 'oauth_token_enc', 'oauth_client_secret_enc'])


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0009_encrypt_backup_secrets'),
    ]

    operations = [
        migrations.RunPython(migrate_backup_data, migrations.RunPython.noop),
    ]
