# Generated by Django 5.2.15 on 2026-06-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0010_migrate_existing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupschedule',
            name='day',
            field=models.IntegerField(default=1, verbose_name='روز ماه (برای بکاپ ماهانه)'),
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='retention_days',
            field=models.IntegerField(default=60, verbose_name='نگهداری بکاپ (روز)'),
        ),
    ]
