# Generated by Django 6.0.5 on 2026-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='آدرس مطب')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن مطب')),
            ],
            options={
                'verbose_name': 'تنظیمات کلینیک',
                'verbose_name_plural': 'تنظیمات کلینیک',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='medical_council_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره نظام پزشکی'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='تخصص'),
        ),
    ]
