# Generated by Django 6.0.5 on 2026-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clinicsetting_user_medical_council_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsetting',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن دوم مطب'),
        ),
    ]
