# Generated by Django 6.0.5 on 2026-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clinicsetting_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsetting',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام کلینیک/مطب'),
        ),
        migrations.AddField(
            model_name='clinicsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinic_logos/', verbose_name='لوگو'),
        ),
    ]
