# Generated by Django 6.0.5 on 2026-05-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clinicsetting_clinic_name_clinicsetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='دسترسی صفحات'),
        ),
    ]
