# Generated by Django 6.0.5 on 2026-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clinicsetting_sms_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsetting',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=300, verbose_name='Token سامانه پیامک (amootsms)'),
        ),
        migrations.AlterField(
            model_name='clinicsetting',
            name='sms_provider',
            field=models.CharField(blank=True, default='amootsms', max_length=20, verbose_name='ارائه\u200cدهنده پیامک'),
        ),
    ]
