# Generated by Django 6.0.5 on 2026-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_clinicsetting_sms_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsetting',
            name='sms_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='رمز عبور سامانه پیامک (ملی پیامک)'),
        ),
        migrations.AddField(
            model_name='clinicsetting',
            name='sms_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام کاربری سامانه پیامک (ملی پیامک)'),
        ),
        migrations.AlterField(
            model_name='clinicsetting',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=300, verbose_name='Token سامانه پیامک (amootsms - قدیمی)'),
        ),
        migrations.AlterField(
            model_name='clinicsetting',
            name='sms_provider',
            field=models.CharField(blank=True, default='melipayamak', max_length=20, verbose_name='ارائه\u200cدهنده پیامک'),
        ),
    ]
