# Generated by Django 6.0.5 on 2026-05-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clinicsetting_sms_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsetting',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=300, verbose_name='API Key سامانه پیامک (ملی پیامک)'),
        ),
    ]
