# Generated by Django 6.0.5 on 2026-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_clinicsetting_sms_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsetting',
            name='sms_api_base',
            field=models.CharField(blank=True, default='https://console.melipayamak.com/api', max_length=300, verbose_name='آدرس API سامانه پیامک'),
        ),
    ]
