# Generated by Django 6.0.5 on 2026-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_clinicsetting_sms_api_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر کلینیک'), ('reception', 'پذیرش'), ('doctor', 'پزشک / درمانگر'), ('super_support', 'پشتیبانی ارشد')], default='reception', max_length=20, verbose_name='نقش'),
        ),
    ]
