# Generated by Django 6.0.5 on 2026-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmenttype',
            name='name',
            field=models.CharField(error_messages={'unique': 'این بخش درمانی قبلاً ثبت شده است'}, max_length=100, unique=True, verbose_name='نام بخش درمانی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر کلینیک'), ('reception', 'پذیرش'), ('doctor', 'پزشک / درمانگر'), ('support', 'پشتیبانی'), ('super_support', 'پشتیبانی ارشد')], default='reception', max_length=20, verbose_name='نقش'),
        ),
    ]
