# Generated by Django 6.0.5 on 2026-06-01 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_clinicsetting_app_title_favicon_colors_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsetting',
            name='app_title',
        ),
        migrations.RemoveField(
            model_name='clinicsetting',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='clinicsetting',
            name='features',
        ),
        migrations.RemoveField(
            model_name='clinicsetting',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='clinicsetting',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='clinicsetting',
            name='sms_api_key',
        ),
        migrations.RemoveField(
            model_name='clinicsetting',
            name='sms_password',
        ),
        migrations.RemoveField(
            model_name='clinicsetting',
            name='sms_username',
        ),
        migrations.AddField(
            model_name='clinicsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicsetting',
            name='sms_api_key_enc',
            field=models.TextField(blank=True, verbose_name='API Key رمزنگاری شده'),
        ),
        migrations.AddField(
            model_name='clinicsetting',
            name='sms_password_enc',
            field=models.TextField(blank=True, verbose_name='رمز عبور رمزنگاری شده'),
        ),
        migrations.AddField(
            model_name='clinicsetting',
            name='sms_username_enc',
            field=models.TextField(blank=True, verbose_name='نام کاربری رمزنگاری شده'),
        ),
        migrations.AddField(
            model_name='clinicsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
