# Generated by Django 6.0.5 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsetting',
            name='phone3',
            field=models.CharField(blank=True, default='09001577080', max_length=20, verbose_name='تلفن سوم مطب'),
        ),
    ]
