# Generated by Django 6.0.6 on 2026-06-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_clinicsetting_phone3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر کلینیک'), ('reception', 'پذیرش'), ('doctor', 'درمانگر'), ('psychologist', 'روانشناس / درمانگر'), ('rtms', 'کاربر ویژه'), ('support', 'پشتیبانی'), ('super_support', 'پشتیبانی ارشد')], default='reception', max_length=20, verbose_name='نقش'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نقش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='دسترسی\u200cها')),
                ('is_system_role', models.BooleanField(default=False, verbose_name='نقش سیستمی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
