# Generated by Django 6.0.6 on 2026-06-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='تایید دو مرحله\u200cای با Google Authenticator'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='کلید مخفی Google Authenticator'),
        ),
    ]
