# Generated by Django 6.0.6 on 2026-06-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_totp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmenttype',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت (تومان)'),
        ),
    ]
