# Generated by Django 5.2.15 on 2026-06-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_update_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ناموفق ورود'),
        ),
    ]
