# Generated by Django 4.2.30 on 2026-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_encrypt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restrictions',
            field=models.JSONField(blank=True, default=dict, verbose_name='محدودیت\u200cها'),
        ),
    ]
