# Generated by Django 6.0.5 on 2026-05-17 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='عملیات')),
                ('model_name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ',
                'verbose_name_plural': 'لاگ\u200cها',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(verbose_name='شماره جلسه')),
                ('date', models.DateField(verbose_name='تاریخ جلسه')),
                ('diagnosis', models.TextField(blank=True, verbose_name='تشخیص')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='طرح درمان')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای پزشک')),
                ('prescription', models.TextField(blank=True, verbose_name='نسخه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment', verbose_name='نوبت مرتبط')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'پرونده درمانی',
                'verbose_name_plural': 'پرونده\u200cهای درمانی',
                'ordering': ['-date', '-session_number'],
                'unique_together': {('patient', 'doctor', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_files/%Y/%m/', verbose_name='فایل')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='medical_records.medicalrecord', verbose_name='پرونده درمانی')),
            ],
            options={
                'verbose_name': 'فایل پرونده',
                'verbose_name_plural': 'فایل\u200cهای پرونده',
            },
        ),
    ]
