# Generated by Django 6.0.5 on 2026-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تشخیص')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تشخیص آماده',
                'verbose_name_plural': 'تشخیص\u200cهای آماده',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CommonDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دارو')),
                ('dosage_unit', models.CharField(default='میلی\u200cگرم', max_length=50, verbose_name='واحد مقدار')),
                ('default_dosage', models.CharField(blank=True, max_length=100, verbose_name='مقدار پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'داروی آماده',
                'verbose_name_plural': 'داروهای آماده',
                'ordering': ['name'],
            },
        ),
    ]
