# Generated by Django 6.0.5 on 2026-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_commondiagnosis_commondrug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonTreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان طرح درمان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'طرح درمان آماده',
                'verbose_name_plural': 'طرح\u200cهای درمان آماده',
                'ordering': ['title'],
            },
        ),
    ]
