# Generated by Django 6.0.5 on 2026-05-29 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_medicalrecord_deleted_at_medicalrecord_deleted_by_and_more'),
        ('patients', '0011_alter_patient_file_number_alter_patient_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TmsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('service_code', models.CharField(default='900115', max_length=20, verbose_name='کد خدمت')),
                ('current_mood', models.TextField(blank=True, verbose_name='خلقی')),
                ('current_psychotic', models.TextField(blank=True, verbose_name='سایکوتیک')),
                ('current_substance', models.TextField(blank=True, verbose_name='ناشی از مواد')),
                ('current_anxiety', models.TextField(blank=True, verbose_name='اضطرابی')),
                ('current_cognitive', models.TextField(blank=True, verbose_name='شناختی')),
                ('current_physical', models.TextField(blank=True, verbose_name='جسمانی')),
                ('current_personality_disorder', models.TextField(blank=True, verbose_name='اختلال شخصیت')),
                ('current_ocd', models.TextField(blank=True, verbose_name='اختلال وسواسی')),
                ('previous_diagnosis', models.TextField(blank=True, verbose_name='تشخیص قبلی')),
                ('current_diagnosis', models.TextField(blank=True, verbose_name='تشخیص فعلی')),
                ('treatment_history', models.TextField(blank=True, verbose_name='سوابق درمانی')),
                ('current_medications', models.TextField(blank=True, verbose_name='داروهای فعلی')),
                ('tms_usage', models.TextField(blank=True, verbose_name='موارد استفاده از TMS')),
                ('qeeg_findings', models.TextField(blank=True, verbose_name='یافته QEEG')),
                ('protocol1', models.TextField(blank=True, verbose_name='پروتکل 1')),
                ('protocol2', models.TextField(blank=True, verbose_name='پروتکل 2')),
                ('protocol3', models.TextField(blank=True, verbose_name='پروتکل 3')),
                ('sessions', models.JSONField(blank=True, default=list, verbose_name='جلسات درمان')),
                ('consent_patient_name', models.CharField(blank=True, max_length=200, verbose_name='نام بیمار در رضایت\u200cنامه')),
                ('consent_father_name', models.CharField(blank=True, max_length=200, verbose_name='نام پدر در رضایت\u200cنامه')),
                ('consent_signature', models.TextField(blank=True, verbose_name='امضای بیمار')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tms_forms_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حذف کننده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_forms', to=settings.AUTH_USER_MODEL, verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tms_forms', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'فرم TMS',
                'verbose_name_plural': 'فرم\u200cهای TMS',
                'ordering': ['-date'],
            },
        ),
    ]
