# Generated by Django 4.2.30 on 2026-06-09 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_records', '0006_medicalrecord_created_by_tmsform_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان قالب')),
                ('category', models.CharField(choices=[('neurology', 'نورولوژی'), ('psychiatry', 'روانپزشکی'), ('general', 'عمومی')], max_length=20, verbose_name='تخصص')),
                ('diagnosis_template', models.TextField(blank=True, verbose_name='الگوی تشخیص')),
                ('treatment_plan_template', models.TextField(blank=True, verbose_name='الگوی طرح درمان')),
                ('notes_template', models.TextField(blank=True, verbose_name='الگوی یادداشت')),
                ('prescription_template', models.TextField(blank=True, verbose_name='الگوی نسخه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_templates', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'قالب ویزیت',
                'verbose_name_plural': 'قالب\u200cهای ویزیت',
                'ordering': ['-created_at'],
            },
        ),
    ]
