# Generated by Django 4.2.30 on 2026-06-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_visittemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/', verbose_name='یادداشت صوتی'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='voice_transcription',
            field=models.TextField(blank=True, verbose_name='متن تشخیص داده شده از صوت'),
        ),
    ]
