# Generated by Django 6.0.6 on 2026-06-10 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0008_medicalrecord_voice_note_and_more'),
        ('patients', '0014_patientportalsession_portalotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicom_files/', verbose_name='فایل DICOM')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='dicom_thumbnails/', verbose_name='تصویر بندانگشتی')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('study_uid', models.CharField(blank=True, max_length=100, verbose_name='شناسه مطالعه')),
                ('series_uid', models.CharField(blank=True, max_length=100, verbose_name='شناسه سری')),
                ('modality', models.CharField(blank=True, max_length=20, verbose_name='مودالیته')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicom_files', to='medical_records.medicalrecord', verbose_name='پرونده پزشکی')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_files', to='patients.patient', verbose_name='بیمار')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلود کننده')),
            ],
            options={
                'verbose_name': 'فایل DICOM',
                'verbose_name_plural': 'فایل\u200cهای DICOM',
                'ordering': ['-created_at'],
            },
        ),
    ]
