# Generated by Django 4.2.30 on 2026-06-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_dicom_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['is_deleted'], name='medical_rec_is_dele_a3ee9c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['doctor', 'date'], name='medical_rec_doctor__0b9acf_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_at'], name='medical_rec_created_3a5a52_idx'),
        ),
    ]
