# Generated by Django 5.2.15 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0010_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsform',
            name='score_c',
            field=models.FloatField(blank=True, null=True, verbose_name='C'),
        ),
        migrations.AddField(
            model_name='tmsform',
            name='score_ni',
            field=models.FloatField(blank=True, null=True, verbose_name='NI'),
        ),
        migrations.AddField(
            model_name='tmsform',
            name='score_tt',
            field=models.FloatField(blank=True, null=True, verbose_name='TT'),
        ),
        migrations.AddField(
            model_name='tmsform',
            name='score_u',
            field=models.FloatField(blank=True, null=True, verbose_name='U'),
        ),
        migrations.AddField(
            model_name='tmsform',
            name='score_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y'),
        ),
        migrations.AddField(
            model_name='tmsform',
            name='score_mt1',
            field=models.FloatField(blank=True, null=True, verbose_name='Mt'),
        ),
        migrations.AddField(
            model_name='tmsform',
            name='score_mt2',
            field=models.FloatField(blank=True, null=True, verbose_name='Mt'),
        ),
        migrations.AddField(
            model_name='tmsform',
            name='score_mt3',
            field=models.FloatField(blank=True, null=True, verbose_name='Mt'),
        ),
        migrations.AddField(
            model_name='tmsform',
            name='score_mt4',
            field=models.FloatField(blank=True, null=True, verbose_name='Mt'),
        ),
    ]
