# Generated by Django 6.0.6 on 2026-06-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(blank=True, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'تنظیمات کلینیک',
                'verbose_name_plural': 'تنظیمات کلینیک',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['-date'],
            },
        ),
    ]
