version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - ALLOWED_HOSTS=tt134.runflare.run,localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://tt134.runflare.run,https://tt134.runflare.run,http://localhost:8000,http://127.0.0.1:8000
      - CSRF_TRUSTED_ORIGINS=http://tt134.runflare.run,https://tt134.runflare.run,http://localhost:8000,http://127.0.0.1:8000
      - DEBUG=False
      - DJANGO_SECRET_KEY=change-this-secret-key-in-production
    volumes:
      - clinic_data:/app/data
      - clinic_media:/app/media
      - clinic_backups:/app/backups

volumes:
  clinic_data:
  clinic_media:
  clinic_backups:
