version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - DJANGO_SECRET_KEY=l2!54moiqslmx@h%s@%jeu#8@=3sjg@*rm(h_qwuz5tp))!a@q
      - ENCRYPTION_KEY=F6xf_lJ5Y7PJTHGOURVQzi0QQRVdRMcVjRft1HvquuE=
      - ALLOWED_HOSTS=tt134.runflare.run,localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://tt134.runflare.run,https://tt134.runflare.run,http://localhost:8000,http://127.0.0.1:8000
      - CSRF_TRUSTED_ORIGINS=http://tt134.runflare.run,https://tt134.runflare.run,http://localhost:8000,http://127.0.0.1:8000
      - DEBUG=False
      - CORS_ALLOW_ALL_ORIGINS=False
    volumes:
      - clinic_data:/app/data
      - clinic_media:/app/media
      - clinic_backups:/app/backups

volumes:
  clinic_data:
  clinic_media:
  clinic_backups:
