# Generated by Django 6.0.5 on 2026-05-17 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ پرداختی')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('insurance', 'بیمه'), ('transfer', 'کارت به کارت')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('doctor_commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد سهم پزشک')),
                ('doctor_share', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='سهم پزشک')),
                ('status', models.CharField(choices=[('pending', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('partial', 'پرداخت جزئی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='appointments.appointment', verbose_name='نوبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billings', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to=settings.AUTH_USER_MODEL, verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'صورتحساب',
                'verbose_name_plural': 'صورتحساب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ تسویه')),
                ('status', models.CharField(default='done', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL, verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'تسویه حساب',
                'verbose_name_plural': 'تسویه حساب\u200cها',
                'ordering': ['-date'],
            },
        ),
    ]
