# Generated by Django 6.0.5 on 2026-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='cost_type',
            field=models.CharField(choices=[('visit', 'ویزیت'), ('service', 'خدمات')], default='visit', max_length=20, verbose_name='نوع هزینه'),
        ),
    ]
