# Generated by Django 6.0.5 on 2026-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billing_deleted_at_billing_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره رسید'),
        ),
    ]
