# Generated by Django 6.0.5 on 2026-06-01 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_created_by_and_more'),
        ('billing', '0004_billing_receipt_number'),
        ('patients', '0012_alter_patient_created_by_alter_patient_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='cost_type',
            field=models.CharField(choices=[('visit', 'ویزیت'), ('service', 'خدمات'), ('visit_service', 'خدمات / ویزیت')], default='visit', max_length=20, verbose_name='نوع هزینه'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حذف کننده'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['patient', 'status'], name='billing_bil_patient_78b819_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['doctor', 'status'], name='billing_bil_doctor__c7a306_idx'),
        ),
    ]
