# Generated by Django 6.0.6 on 2026-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_billing_cost_type_alter_billing_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='authority',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد ارجاع'),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس پرداخت'),
        ),
        migrations.AddField(
            model_name='billing',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره تراکنش'),
        ),
    ]
