# Generated by Django 6.0.6 on 2026-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billing_authority_billing_payment_url_billing_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='period_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='برچسب دوره'),
        ),
        migrations.AddField(
            model_name='billing',
            name='period_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='ماه دوره'),
        ),
        migrations.AddField(
            model_name='billing',
            name='period_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال دوره'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='cost_type',
            field=models.CharField(choices=[('visit', 'ویزیت'), ('service', 'خدمات'), ('visit_service', 'خدمات / ویزیت'), ('periodic', 'دوره‌ای')], default='visit', max_length=20, verbose_name='نوع هزینه'),
        ),
    ]
