# Generated by Django 6.0.6 on 2026-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billing_period_label_billing_period_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('insurance', 'بیمه'), ('transfer', 'کارت به کارت'), ('in_person', 'حضوری'), ('online', 'آنلاین')], default='cash', max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
