# Generated by Django 4.2.30 on 2026-06-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_billing_payment_method'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['is_deleted'], name='billing_bil_is_dele_a90110_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['created_at'], name='billing_bil_created_50c285_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['patient', 'created_at'], name='billing_bil_patient_8d2ce1_idx'),
        ),
    ]
