# Generated by Django 6.0.5 on 2026-05-17 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='ساعت')),
                ('status', models.CharField(choices=[('scheduled', 'نوبت\u200cگذاری شده'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده'), ('rescheduled', 'تغییر یافته')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='پیامک ارسال شد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='بیمار')),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.treatmenttype', verbose_name='نوع درمان')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date', 'doctor'], name='appointment_date_a3fbbd_idx'), models.Index(fields=['patient', 'status'], name='appointment_patient_44acdc_idx')],
            },
        ),
    ]
