# Generated by Django 6.0.5 on 2026-05-23 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role'),
        ('appointments', '0002_appointment_cost'),
        ('patients', '0008_referralletter_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='شناسه منبع خارجی'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='منبع نوبت'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['source'], name='appointment_source_02dbdc_idx'),
        ),
    ]
