# Generated by Django 6.0.5 on 2026-05-29 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_external_id_appointment_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حذف کننده'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
