# Generated by Django 6.0.5 on 2026-05-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_deleted_at_appointment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_cost',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='هزینه خدمات'),
        ),
    ]
