# Generated by Django 6.0.6 on 2026-06-09 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0013_patienttag_patienttagassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='هش اثر انگشت')),
                ('fingerprint_data', models.TextField(blank=True, null=True, verbose_name='داده اثر انگشت')),
                ('id_card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره شناسنامه')),
                ('id_card_serial', models.CharField(blank=True, max_length=20, verbose_name='سریال شناسنامه')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='محل تولد')),
                ('nationality', models.CharField(default='ایرانی', max_length=50, verbose_name='ملیت')),
                ('religion', models.CharField(blank=True, max_length=50, verbose_name='دین')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='گروه خونی')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='نام شخص اضطراری')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='نسبت شخص اضطراری')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن شخص اضطراری')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید هویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='patients.patient', verbose_name='بیمار')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
            ],
            options={
                'verbose_name': 'هویت بیمار',
                'verbose_name_plural': 'هویت بیماران',
            },
        ),
    ]
