# Generated by Django 5.2.15 on 2026-06-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientidentity',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patientidentity',
            name='fingerprint_data',
        ),
        migrations.RemoveField(
            model_name='patientidentity',
            name='id_card_number',
        ),
        migrations.RemoveField(
            model_name='patientidentity',
            name='id_card_serial',
        ),
        migrations.RemoveField(
            model_name='patientidentity',
            name='notes',
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='emergency_contact_phone_enc',
            field=models.TextField(blank=True, verbose_name='تلفن شخص اضطراری (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='emergency_contact_phone_raw',
            field=models.CharField(blank=True, max_length=15, verbose_name='تلفن شخص اضطراری (قدیمی)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='fingerprint_data_enc',
            field=models.TextField(blank=True, null=True, verbose_name='داده اثر انگشت (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='fingerprint_data_raw',
            field=models.TextField(blank=True, null=True, verbose_name='داده اثر انگشت (قدیمی)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='id_card_number_enc',
            field=models.TextField(blank=True, verbose_name='شماره شناسنامه (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='id_card_number_raw',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره شناسنامه (قدیمی)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='id_card_serial_enc',
            field=models.TextField(blank=True, verbose_name='سریال شناسنامه (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='id_card_serial_raw',
            field=models.CharField(blank=True, max_length=20, verbose_name='سریال شناسنامه (قدیمی)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='notes_enc',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها (رمزنگاری شده)'),
        ),
        migrations.AddField(
            model_name='patientidentity',
            name='notes_raw',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها (قدیمی)'),
        ),
    ]
