# Generated by Django 5.2.15 on 2026-06-15 00:35

from django.db import migrations
from utils.encryption import encrypt_value


def migrate_identity_data(apps, schema_editor):
    PatientIdentity = apps.get_model('patient_identity', 'PatientIdentity')
    for obj in PatientIdentity.objects.all():
        changed = False

        if obj.emergency_contact_phone_raw and not obj.emergency_contact_phone_enc:
            obj.emergency_contact_phone_enc = encrypt_value(obj.emergency_contact_phone_raw)
            changed = True

        if obj.fingerprint_data_raw and not obj.fingerprint_data_enc:
            obj.fingerprint_data_enc = encrypt_value(obj.fingerprint_data_raw)
            changed = True

        if obj.id_card_number_raw and not obj.id_card_number_enc:
            obj.id_card_number_enc = encrypt_value(obj.id_card_number_raw)
            changed = True

        if obj.id_card_serial_raw and not obj.id_card_serial_enc:
            obj.id_card_serial_enc = encrypt_value(obj.id_card_serial_raw)
            changed = True

        if obj.notes_raw and not obj.notes_enc:
            obj.notes_enc = encrypt_value(obj.notes_raw)
            changed = True

        if changed:
            obj.save(update_fields=[
                'emergency_contact_phone_enc',
                'fingerprint_data_enc',
                'id_card_number_enc',
                'id_card_serial_enc',
                'notes_enc',
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('patient_identity', '0002_encrypt_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_identity_data, migrations.RunPython.noop),
    ]
