# Generated by Django 6.0.5 on 2026-05-23 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_cost'),
        ('patients', '0007_patient_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('template_type', models.CharField(choices=[('confirm', 'تأیید نوبت'), ('reminder', 'یادآوری نوبت'), ('payment', 'یادآوری پرداخت')], max_length=20, unique=True, verbose_name='نوع قالب')),
                ('pattern_code', models.CharField(help_text='کد الگو که در پنل amootsms دریافت کردید', max_length=50, verbose_name='کد الگو (Pattern Code)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('patient_name', models.CharField(blank=True, max_length=200, verbose_name='نام بیمار')),
                ('message_type', models.CharField(choices=[('confirm', 'تأیید نوبت'), ('reminder', 'یادآوری نوبت'), ('payment', 'یادآوری پرداخت')], max_length=20, verbose_name='نوع پیام')),
                ('send_method', models.CharField(choices=[('bulk', 'ارسال گروهی (Bulk)'), ('verify', 'ارسال قالب (Verify)')], max_length=20, verbose_name='روش ارسال')),
                ('status', models.CharField(choices=[('pending', 'در حال ارسال'), ('sent', 'ارسال شد'), ('failed', 'خطا در ارسال')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('template_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه قالب')),
                ('line_number', models.CharField(blank=True, max_length=20, verbose_name='شماره خط')),
                ('message_text', models.TextField(verbose_name='متن پیام')),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پیام در amootsms')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه (تومان)')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='appointments.appointment', verbose_name='نوبت مرتبط')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='patients.patient', verbose_name='بیمار مرتبط')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
            ],
            options={
                'verbose_name': 'تاریخچه پیامک',
                'verbose_name_plural': 'تاریخچه پیامک\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sms_notific_created_e99e2b_idx'), models.Index(fields=['status'], name='sms_notific_status_c7e998_idx'), models.Index(fields=['phone_number'], name='sms_notific_phone_n_d86b99_idx')],
            },
        ),
    ]
