# Generated by Django 6.0.5 on 2026-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='pattern_code',
            field=models.CharField(help_text='شناسه الگو (bodyId) که در پنل ملی پیامک دریافت کردید', max_length=50, verbose_name='کد الگو (bodyId)'),
        ),
    ]
