# Generated by Django 6.0.5 on 2026-05-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0002_alter_smstemplate_pattern_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='template_type',
            field=models.CharField(choices=[('confirm', 'تأیید نوبت'), ('reminder', 'یادآوری نوبت'), ('payment', 'یادآوری پرداخت'), ('otp', 'کد تایید')], max_length=20, unique=True, verbose_name='نوع قالب'),
        ),
    ]
