# Generated by Django 6.0.5 on 2026-05-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0003_add_otp_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='message_type',
            field=models.CharField(choices=[('confirm', 'تأیید نوبت'), ('reminder', 'یادآوری نوبت'), ('payment', 'یادآوری پرداخت'), ('otp', 'کد تایید')], max_length=20, verbose_name='نوع پیام'),
        ),
    ]
