# Generated by Django 6.0.5 on 2026-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0004_add_otp_and_ip_to_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='template_type',
            field=models.CharField(choices=[('confirm', 'تأیید نوبت'), ('reminder', 'یادآوری نوبت'), ('payment', 'یادآوری پرداخت'), ('otp', 'کد تایید')], error_messages={'unique': 'این نوع قالب قبلاً ثبت شده است'}, max_length=20, unique=True, verbose_name='نوع قالب'),
        ),
    ]
