# Generated by Django 6.0.5 on 2026-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0005_alter_smstemplate_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger_type', models.CharField(choices=[('eitaa', 'ایتا'), ('bale', 'بله'), ('rubika', 'روبیکا')], error_messages={'unique': 'این پیام‌رسان قبلاً ثبت شده است'}, max_length=20, unique=True, verbose_name='نوع پیام‌رسان')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('bot_token', models.CharField(blank=True, max_length=255, verbose_name='توکن ربات')),
                ('chat_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه گیرنده پیش‌فرض')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات پیام‌رسان',
                'verbose_name_plural': 'تنظیمات پیام‌رسان‌ها',
                'ordering': ['messenger_type'],
            },
        ),
        migrations.CreateModel(
            name='MessengerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger_type', models.CharField(max_length=20, verbose_name='نوع پیام‌رسان')),
                ('recipient', models.CharField(max_length=100, verbose_name='گیرنده')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'خطا در ارسال')], max_length=20, verbose_name='وضعیت')),
                ('message_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه پیام')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'تاریخچه پیام پیام‌رسان',
                'verbose_name_plural': 'تاریخچه پیام‌های پیام‌رسان',
                'ordering': ['-created_at'],
            },
        ),
    ]
