# Generated by Django 5.2.15 on 2026-06-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_notifications', '0006_messengersetting_messengerlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengersetting',
            name='messenger_type',
            field=models.CharField(choices=[('bale', 'بله')], error_messages={'unique': 'این پیام\u200cرسان قبلاً ثبت شده است'}, max_length=20, unique=True, verbose_name='نوع پیام\u200cرسان'),
        ),
    ]
