ALL_PAGES = [
    {'codename': 'dashboard', 'name': 'داشبورد', 'group': 'عمومی'},
    {'codename': 'dashboard_income', 'name': 'نمایش درآمد در داشبورد', 'group': 'عمومی'},
    {'codename': 'patients', 'name': 'مدیریت بیماران', 'group': 'بیماران'},
    {'codename': 'patient_info', 'name': 'اطلاعات فردی بیمار', 'group': 'بیماران'},
    {'codename': 'patient_appointments', 'name': 'نوبت‌های بیمار', 'group': 'بیماران'},
    {'codename': 'patient_records', 'name': 'پرونده پزشکی در بیمار', 'group': 'بیماران'},
    {'codename': 'patient_billing', 'name': 'صورتحساب در بیمار', 'group': 'بیماران'},
    {'codename': 'patient_create', 'name': 'ثبت بیمار جدید', 'group': 'بیماران'},
    {'codename': 'patient_view', 'name': 'مشاهده اطلاعات بیمار', 'group': 'بیماران'},
    {'codename': 'patient_edit', 'name': 'ویرایش اطلاعات بیمار', 'group': 'بیماران'},
    {'codename': 'patient_delete', 'name': 'حذف بیمار', 'group': 'بیماران'},
    {'codename': 'appointments', 'name': 'نوبت‌ها', 'group': 'نوبت‌ها'},
    {'codename': 'appointments_calendar', 'name': 'تقویم نوبت‌ها', 'group': 'نوبت‌ها'},
    {'codename': 'waiting_list', 'name': 'لیست انتظار', 'group': 'نوبت‌ها'},
    {'codename': 'appointments_report', 'name': 'گزارش نوبت‌ها', 'group': 'نوبت‌ها'},
    {'codename': 'medical_records', 'name': 'پرونده پزشکی', 'group': 'پزشکی'},
    {'codename': 'doctor_finance', 'name': 'حساب پزشکان', 'group': 'پزشکی'},
    {'codename': 'referral_letters', 'name': 'نامه‌های ارجاع', 'group': 'پزشکی'},
    {'codename': 'diagnosis_report', 'name': 'گزارش تشخیص', 'group': 'پزشکی'},
    {'codename': 'diagnosis_drugs', 'name': 'تشخیص و دارو', 'group': 'پزشکی'},
    {'codename': 'billing', 'name': 'صورتحساب', 'group': 'مالی'},
    {'codename': 'billing_report', 'name': 'گزارش مالی', 'group': 'مالی'},
    {'codename': 'settlements', 'name': 'تسویه حساب', 'group': 'مالی'},
    {'codename': 'notifications', 'name': 'اعلانات', 'group': 'مدیریت سیستم'},
    {'codename': 'users', 'name': 'کاربران', 'group': 'مدیریت سیستم'},
    {'codename': 'backup', 'name': 'پشتیبان', 'group': 'مدیریت سیستم'},
    {'codename': 'settings', 'name': 'تنظیمات', 'group': 'مدیریت سیستم'},
    {'codename': 'support_inbox', 'name': 'صندوق پیام‌های پشتیبانی', 'group': 'پشتیبانی'},
    {'codename': 'show_appointments_menu', 'name': 'نمایش منوی نوبت‌ها (به همراه زیرمنو)', 'group': 'نمایش منوها'},
    {'codename': 'show_medical_menu', 'name': 'نمایش منوی پزشکی (به همراه زیرمنو)', 'group': 'نمایش منوها'},
    {'codename': 'show_financial_menu', 'name': 'نمایش منوی مالی (به همراه زیرمنو)', 'group': 'نمایش منوها'},
    {'codename': 'show_system_menu', 'name': 'نمایش منوی مدیریت سیستم (به همراه زیرمنو)', 'group': 'نمایش منوها'},
        {'codename': 'special_access', 'name': 'کاربر ویژه', 'group': 'عمومی'},
]

DEFAULT_ROLE_PERMISSIONS = {
    'admin': [p['codename'] for p in ALL_PAGES],
    'super_support': [p['codename'] for p in ALL_PAGES],
    'support': [p['codename'] for p in ALL_PAGES],
    'reception': ['dashboard', 'patients', 'patient_info', 'patient_appointments',
                  'patient_billing', 'patient_create', 'patient_view', 'patient_edit',
                  'appointments', 'appointments_calendar',
                  'waiting_list', 'billing', 'doctor_finance', 'settlements'],
    'doctor': ['dashboard', 'dashboard_income', 'patients', 'patient_info',
               'patient_appointments', 'patient_records', 'patient_billing',
               'patient_create', 'patient_view', 'patient_edit',
               'appointments', 'appointments_calendar', 'waiting_list',
               'medical_records', 'doctor_finance', 'referral_letters',
               'diagnosis_report', 'diagnosis_drugs'],
    'rtms': ['dashboard', 'patients', 'patient_info',
             'patient_appointments', 'patient_billing',
             'patient_create', 'patient_view', 'patient_edit',
             'appointments', 'appointments_calendar', 'waiting_list',
             'medical_records', 'doctor_finance', 'referral_letters',
             'diagnosis_report', 'diagnosis_drugs'],
}
